DefaultContentLanguage = "en"
author = "Kim Min Jae"
baseURL = "https://gamjagoon.github.io/asdf"
copyright = "Copyright © 2008–2021, Steve Francia and the Hugo Authors; all rights reserved."
disqusShortname = "minjae-blog-1"
enableEmoji = true
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
ignoreErrors = ["error-remote-getjson"]
languageCode = "en"
paginate = 3
summaryLength = 20
theme = "monopriv_mj"
title = "Sweet Potato"
[params]
about = "Embedded systems and verilog designs"
analytics = false
disqus = true
email = "rlaalswo201@gmail.com"
github = "https://github.com/gamjagoon"
metadesc = "A simple privacy oriented bootstrap hugo blog"
metakeys = "verilog, FPGA, Python, AI, cryptography"

[params.search] # Site search powered by DuckDuckGo
enabled = true
placeholder = "Site Search"

[params.hero]
enabled = true
img = "img/logo2.jpg"

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[privacy]

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services]

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
